# правая половинка (peripheral) — анимация gem
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_GEM=y
# другие варианты (раскомментировать одну, закомментировать gem):
# CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=y
# CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_POKEMON=y
# CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN=y
# CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_HEAD=y
